http:
  servers:
    - listen: 8080
      logger: true
      location:
        - path: /api/hello
          method: GET
          response: '{"message": "Hello, World!"}'
          status_code: 200
          headers:
            Content-Type: application/json
        - path: /api/echo
          method: POST
          schema: |
            {
              "type": "object",
              "properties": {
                "message": { "type": "string" }
              },
              "required": ["message"]
            }
          response: '{"echo": "{{.message}}"}'
          status_code: 200
          headers:
            Content-Type: application/json
    - listen: 8081
      logger: false
      chaos_injection:
        latency:
          time: 100
          probability: "50"
        abort:
          code: 500
          probability: "10"
        error:
          code: 400
          probability: "5"
      location:
        - path: /api/data
          method: GET
          response: '{"data": [1, 2, 3, 4, 5]}'
          status_code: 200
          headers:
            Content-Type: application/json
        - path: /api/async
          method: POST
          response: '{"status": "processing"}'
          status_code: 202
          async:
            url: http://localhost:8080/api/callback
            method: POST
            body: '{"result": "success"}'
            timeout: 5000
            retries: 3
            retry_delay: 1000
            headers:
              Content-Type: application/json